### ISSUE TITLE
bind persistence-layer to default home directory

### ISSUE THREAD

**Issue by capsulecorplab** [geoCML/geocml-base-deployment#57]
As to save the added step of having to change into a nested directory to persist files during a vnc session

**Comment by TristanDamron** [comment]
Do you want to have the persistence layer as a directory in the home directory, or do you want to replace the home directory with the persistence layer? If it's the latter, we can't do that with our new geocml-desktop base image since /home/headless/ comes preconfigured with VNC session/Xsession configuration file that we should not/cannot change.

**Comment by capsulecorplab** [comment]
Preferably replace the home directory with the persistence layer, but if that's not possible because `/home/headless` shouldn't be changed, then perhaps we can create a new default user under `/home` and bind the persistence layer to that path?

**Comment by TristanDamron** [comment]
I don't really like that; When you're connected to geocml-desktop, you shouldn't be signed in as any other user than headless.

**Comment by TristanDamron** [comment]
Additionally, the persistence layer is now bound to several geoCML services (see docker-compose.yml). While I can see your argument that it might make sense for the persistence layer to act as a home directory for geocml-desktop, it doesn't make sense for geocml-task-scheduler or geocml-server.

**Comment by capsulecorplab** [comment]
So the `geocml-task-scheduler` or `geocml-server` can only be accessed by the `headless` user?

**Comment by TristanDamron** [comment]
No, geocml-task-scheduler and geocml-server are separate containers so they each have separate users accessing the persistence layer.

**Comment by TristanDamron** [comment]
Can I close this issue and mark it 'as-designed'?

**Comment by capsulecorplab** [comment]
Sorry, I'm still a bit confused; I guess I'm not understanding why the default user has to be tethered to headless and why it's a bad design for `geocml-task-scheduler` and `geocml-server` if that were to change.

**Comment by TristanDamron** [comment]
_headless is the default user preconfigured for ubuntu-vnc-xfce-g3_ (used in geocml-desktop). We should not (and more importantly, **_cannot_**) overwrite this user otherwise we will break geocml-desktop (i.e. we won't have the ability to connect to the desktop client via VNC). Additionally, we cannot start the VNC session as another user without doing all of the Xsession/VNC configuration ourselves. _ubuntu-vnc-xfce-g3 does all of this for free for the headless user_. Please read the documentation for that base image: https://github.com/accetto/ubuntu-vnc-xfce-g3

geocml-server and geocml-task-scheduler _do not use the headless user_ because they are separate containers built from different base images. For each service, the persistence layer is simply used to transfer data files between them. It is because of this that it _does not make sense to make the persistence layer a home directory_. Rather, the persistence layer should only hold files that A) you want to persist between sessions or B) you want to persist between services.
